### ISSUE TITLE
an idea.

### ISSUE THREAD

**Issue by fulbournlad** [ckdextergames/Icarus_mods#2]
HI.

any chance you could make a mod for the deep miners to be faster and use less biofuel. both of them please. oh and a bigger inventory as well. thank you

**Comment by ckdextergames** [comment]
I thought there's others that already do so, but I can check.

Sorry I didn't get back to you earlier, just saw this now. For faster
response, hit me up on discord.

If I don't hear from you there, I'll get back to you via email soon.
Cheers

**Comment by ckdextergames** [comment]
Floof's mod pack has this feature:

https://gitlab.floofsnetwork.xyz/icarus-modding/Mods/-/tree/master/TheOrangeFloof

**Comment by fulbournlad** [comment]
ooh thank you.
________________________________
